[tool.poetry]
name = "campus-classroom"
version = "0.1.0"
description = "Campus Classroom - Assignment Platform for Google Classroom"
authors = ["NYJC Computing <nyjc.computing@nyjc.edu.sg>"]
readme = "README.md"
packages = [{include = "apps/classroom"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
flask = "^3.0.0"

# Campus internal dependencies
campus-api-python = {git = "https://github.com/nyjc-computing/campus-api-python.git", branch = "main"}
campus-suite = {git = "https://github.com/nyjc-computing/campus.git", branch = "weekly"}
python-dotenv = "^1.2.1"

[tool.pyright]
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
